//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.16 at 04:20:24 PM IST 
//


package generated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DomainConfig }
     * 
     */
    public DomainConfig createDomainConfig() {
        return new DomainConfig();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices }
     * 
     */
    public DomainConfig.Devices createDomainConfigDevices() {
        return new DomainConfig.Devices();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Memballoon }
     * 
     */
    public DomainConfig.Devices.Memballoon createDomainConfigDevicesMemballoon() {
        return new DomainConfig.Devices.Memballoon();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Console }
     * 
     */
    public DomainConfig.Devices.Console createDomainConfigDevicesConsole() {
        return new DomainConfig.Devices.Console();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Serial }
     * 
     */
    public DomainConfig.Devices.Serial createDomainConfigDevicesSerial() {
        return new DomainConfig.Devices.Serial();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Disk }
     * 
     */
    public DomainConfig.Devices.Disk createDomainConfigDevicesDisk() {
        return new DomainConfig.Devices.Disk();
    }

    /**
     * Create an instance of {@link DomainConfig.Os }
     * 
     */
    public DomainConfig.Os createDomainConfigOs() {
        return new DomainConfig.Os();
    }

    /**
     * Create an instance of {@link DomainConfig.Clock }
     * 
     */
    public DomainConfig.Clock createDomainConfigClock() {
        return new DomainConfig.Clock();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Input }
     * 
     */
    public DomainConfig.Devices.Input createDomainConfigDevicesInput() {
        return new DomainConfig.Devices.Input();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Graphics }
     * 
     */
    public DomainConfig.Devices.Graphics createDomainConfigDevicesGraphics() {
        return new DomainConfig.Devices.Graphics();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Memballoon.Address }
     * 
     */
    public DomainConfig.Devices.Memballoon.Address createDomainConfigDevicesMemballoonAddress() {
        return new DomainConfig.Devices.Memballoon.Address();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Console.Target }
     * 
     */
    public DomainConfig.Devices.Console.Target createDomainConfigDevicesConsoleTarget() {
        return new DomainConfig.Devices.Console.Target();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Serial.Target }
     * 
     */
    public DomainConfig.Devices.Serial.Target createDomainConfigDevicesSerialTarget() {
        return new DomainConfig.Devices.Serial.Target();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Disk.Driver }
     * 
     */
    public DomainConfig.Devices.Disk.Driver createDomainConfigDevicesDiskDriver() {
        return new DomainConfig.Devices.Disk.Driver();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Disk.Source }
     * 
     */
    public DomainConfig.Devices.Disk.Source createDomainConfigDevicesDiskSource() {
        return new DomainConfig.Devices.Disk.Source();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Disk.Target }
     * 
     */
    public DomainConfig.Devices.Disk.Target createDomainConfigDevicesDiskTarget() {
        return new DomainConfig.Devices.Disk.Target();
    }

    /**
     * Create an instance of {@link DomainConfig.Devices.Disk.Address }
     * 
     */
    public DomainConfig.Devices.Disk.Address createDomainConfigDevicesDiskAddress() {
        return new DomainConfig.Devices.Disk.Address();
    }

    /**
     * Create an instance of {@link DomainConfig.Os.Type }
     * 
     */
    public DomainConfig.Os.Type createDomainConfigOsType() {
        return new DomainConfig.Os.Type();
    }

    /**
     * Create an instance of {@link DomainConfig.Os.Boot }
     * 
     */
    public DomainConfig.Os.Boot createDomainConfigOsBoot() {
        return new DomainConfig.Os.Boot();
    }

}
