//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.18 at 02:37:07 PM IST 
//


package generated;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CapabilitiesGuestArchDomainEmulator_QNAME = new QName("", "emulator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Capabilities }
     * 
     */
    public Capabilities createCapabilities() {
        return new Capabilities();
    }

    /**
     * Create an instance of {@link Capabilities.Guest }
     * 
     */
    public Capabilities.Guest createCapabilitiesGuest() {
        return new Capabilities.Guest();
    }

    /**
     * Create an instance of {@link Capabilities.Guest.Features }
     * 
     */
    public Capabilities.Guest.Features createCapabilitiesGuestFeatures() {
        return new Capabilities.Guest.Features();
    }

    /**
     * Create an instance of {@link Capabilities.Guest.Arch }
     * 
     */
    public Capabilities.Guest.Arch createCapabilitiesGuestArch() {
        return new Capabilities.Guest.Arch();
    }

    /**
     * Create an instance of {@link Capabilities.Host }
     * 
     */
    public Capabilities.Host createCapabilitiesHost() {
        return new Capabilities.Host();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Topology }
     * 
     */
    public Capabilities.Host.Topology createCapabilitiesHostTopology() {
        return new Capabilities.Host.Topology();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Topology.Cells }
     * 
     */
    public Capabilities.Host.Topology.Cells createCapabilitiesHostTopologyCells() {
        return new Capabilities.Host.Topology.Cells();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Topology.Cells.Cell }
     * 
     */
    public Capabilities.Host.Topology.Cells.Cell createCapabilitiesHostTopologyCellsCell() {
        return new Capabilities.Host.Topology.Cells.Cell();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Topology.Cells.Cell.Cpus }
     * 
     */
    public Capabilities.Host.Topology.Cells.Cell.Cpus createCapabilitiesHostTopologyCellsCellCpus() {
        return new Capabilities.Host.Topology.Cells.Cell.Cpus();
    }

    /**
     * Create an instance of {@link Capabilities.Host.MigrationFeatures }
     * 
     */
    public Capabilities.Host.MigrationFeatures createCapabilitiesHostMigrationFeatures() {
        return new Capabilities.Host.MigrationFeatures();
    }

    /**
     * Create an instance of {@link Capabilities.Guest.Features.Acpi }
     * 
     */
    public Capabilities.Guest.Features.Acpi createCapabilitiesGuestFeaturesAcpi() {
        return new Capabilities.Guest.Features.Acpi();
    }

    /**
     * Create an instance of {@link Capabilities.Guest.Features.Apic }
     * 
     */
    public Capabilities.Guest.Features.Apic createCapabilitiesGuestFeaturesApic() {
        return new Capabilities.Guest.Features.Apic();
    }

    /**
     * Create an instance of {@link Capabilities.Guest.Arch.Domain }
     * 
     */
    public Capabilities.Guest.Arch.Domain createCapabilitiesGuestArchDomain() {
        return new Capabilities.Guest.Arch.Domain();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Cpu }
     * 
     */
    public Capabilities.Host.Cpu createCapabilitiesHostCpu() {
        return new Capabilities.Host.Cpu();
    }

    /**
     * Create an instance of {@link Capabilities.Host.Topology.Cells.Cell.Cpus.Cpu }
     * 
     */
    public Capabilities.Host.Topology.Cells.Cell.Cpus.Cpu createCapabilitiesHostTopologyCellsCellCpusCpu() {
        return new Capabilities.Host.Topology.Cells.Cell.Cpus.Cpu();
    }

    /**
     * Create an instance of {@link Capabilities.Host.MigrationFeatures.UriTransports }
     * 
     */
    public Capabilities.Host.MigrationFeatures.UriTransports createCapabilitiesHostMigrationFeaturesUriTransports() {
        return new Capabilities.Host.MigrationFeatures.UriTransports();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "emulator", scope = Capabilities.Guest.Arch.Domain.class)
    public JAXBElement<String> createCapabilitiesGuestArchDomainEmulator(String value) {
        return new JAXBElement<String>(_CapabilitiesGuestArchDomainEmulator_QNAME, String.class, Capabilities.Guest.Arch.Domain.class, value);
    }

}
